interface PortfolioPageProps {
  params: {
    username: string;
  };
}

export default function PortfolioPage({ params }: PortfolioPageProps) {
  return (
    <div className="max-w-4xl mx-auto py-12 px-4">
      <header className="mb-12">
        <h1 className="text-4xl font-bold">@{params.username}</h1>
        <p className="text-xl text-muted-foreground">Portfolio generated by GitFolio</p>
      </header>
    </div>
  );
}
